import ExcelJS from "exceljs";
import path from "path";

/**
 * 產生包含 25+ 題之超大型複雜示範問卷 Excel (demo-complex-survey.xlsx)
 * 涵蓋所有 6 大題型與 15+ 種業務防呆及計分規則
 */
export async function generateComplexSurveyExcel(outputPath: string) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Survey System MVP";
  workbook.created = new Date();

  // 1. Questions Sheet
  const questionsSheet = workbook.addWorksheet("questions");
  questionsSheet.columns = [
    { header: "order_num", key: "order_num", width: 10 },
    { header: "code", key: "code", width: 18 },
    { header: "title", key: "title", width: 45 },
    { header: "description", key: "description", width: 40 },
    { header: "question_type", key: "question_type", width: 18 },
    { header: "required", key: "required", width: 12 },
    { header: "scoring_enabled", key: "scoring_enabled", width: 15 },
    { header: "reverse_score", key: "reverse_score", width: 14 },
    { header: "visibility_rules", key: "visibility_rules", width: 45 },
    { header: "visibility_hint", key: "visibility_hint", width: 40 },
    { header: "min_selections", key: "min_selections", width: 15 },
    { header: "max_selections", key: "max_selections", width: 15 },
    { header: "min_value", key: "min_value", width: 12 },
    { header: "max_value", key: "max_value", width: 12 },
  ];

  const questionsData = [
    // 區塊 1: 基礎滿意度與條件跳題 (Q1 ~ Q3)
    {
      order_num: 1,
      code: "Q1",
      title: "您對本系統整體運作的滿意度為何？ (計分單選 1~4分)",
      description: "測試基礎單選計分題",
      question_type: "single_choice",
      required: true,
      scoring_enabled: true,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 2,
      code: "Q1_FEEDBACK",
      title: "請告訴我們您感到不滿意的主要原因？ (條件顯示題)",
      description: "使用中文 Label 簡寫語法條件跳題",
      question_type: "text",
      required: true,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: "SHOW IF Q1 in [非常不滿意, 不太滿意]",
      visibility_hint: "💡 依據您對滿意度的反饋，請協助補充以下原因：",
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 3,
      code: "Q1_PRAISE",
      title: "感謝肯定！請問您最驚艷的亮點是什麼？ (條件顯示題)",
      description: "使用 equals 條件語法跳題",
      question_type: "text",
      required: false,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: "SHOW IF Q1 equals 非常滿意",
      visibility_hint: "💡 感謝您的滿分好評！請分享您最喜歡的部分：",
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },

    // 區塊 2: 是非題與說明卡片 (Q4 ~ Q5)
    {
      order_num: 4,
      code: "Q2_YESNO",
      title: "您是否曾參加過本系統的線上教學研討會？ (是非題)",
      description: "測試 yes_no 題型",
      question_type: "yes_no",
      required: true,
      scoring_enabled: true,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 5,
      code: "INFO_SECTION_1",
      title: "【模組評估階段說明】以下將針對進階功能進行深入調查",
      description: "純說明資訊卡片，不需作答亦不計分",
      question_type: "info",
      required: false,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },

    // 區塊 3: 數值範圍題 (Q6 ~ Q8)
    {
      order_num: 6,
      code: "Q3_USAGE_FREQ",
      title: "您每週平均使用本系統幾天？ (數值限制 0~7 天)",
      description: "測試數值 min 0, max 7",
      question_type: "number",
      required: true,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: 0,
      max_value: 7,
    },
    {
      order_num: 7,
      code: "Q3_DAILY_HOURS",
      title: "每天平均使用時數？ (數值限制 0.5~24 小時)",
      description: "支援小數點數值範圍",
      question_type: "number",
      required: false,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: 0.5,
      max_value: 24,
    },
    {
      order_num: 8,
      code: "Q3_HIGH_USAGE_REASON",
      title: "高頻重度使用者專屬追問：您主要執行的核心工作流程是？",
      description: "測試數值比較跳題 (SHOW IF Q3_USAGE_FREQ >= 5)",
      question_type: "text",
      required: true,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: "SHOW IF Q3_USAGE_FREQ >= 5",
      visibility_hint: "💡 您為高頻使用者，請協助補充核心工作流程：",
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },

    // 區塊 4: 複選題與選項限制 (Q9 ~ Q11)
    {
      order_num: 9,
      code: "Q4_FEATURES_WANTED",
      title: "您期望未來優先加入的功能？ (複選限選 1~2 項，計分)",
      description: "測試 min_selections=1, max_selections=2",
      question_type: "multiple_choice",
      required: true,
      scoring_enabled: true,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: 1,
      max_selections: 2,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 10,
      code: "Q4_INTEGRATIONS",
      title: "您目前已在使用的第三方整合工具？ (複選含「以上皆非」與「其他」)",
      description: "測試以上皆非互斥 + 其他文字輸入",
      question_type: "multiple_choice",
      required: true,
      scoring_enabled: true,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 11,
      code: "Q4_SLACK_DETAIL",
      title: "Slack 整合模組回饋：請描述您使用的 Webhook 觸發情境",
      description: "測試複選 contains 標籤跳題 (SHOW IF Q4_INTEGRATIONS contains Slack)",
      question_type: "text",
      required: false,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: "SHOW IF Q4_INTEGRATIONS contains Slack",
      visibility_hint: "💡 偵測到您使用 Slack 整合，請分享您的應用情境：",
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },

    // 區塊 5: 特殊分數與不計分區分 (Q12 ~ Q15)
    {
      order_num: 12,
      code: "Q5_TECHNICAL_LEVEL",
      title: "您的技術架構評估等級？ (特殊計分：選項4得10分大獎勵)",
      description: "測試非線性特殊給分 (1, 2, 3, 10)",
      question_type: "single_choice",
      required: true,
      scoring_enabled: true,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 13,
      code: "Q5_OUTAGE_HISTORY",
      title: "過去半年您是否曾遇過系統斷線？ (測試 0 分與 NULL 嚴格區分)",
      description: "選項1為0分(計入分母)，選項2為5分，選項3為NULL(不計分)",
      question_type: "single_choice",
      required: true,
      scoring_enabled: true,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 14,
      code: "Q5_REVERSE_CONFUSION",
      title: "系統設定選項是否過於複雜難懂？ (反向計分題 1~5分反轉)",
      description: "負向題：選非常同意(5分)實際得1分，選非常不同意(1分)實際得5分",
      question_type: "single_choice",
      required: true,
      scoring_enabled: true,
      reverse_score: true,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 15,
      code: "Q5_OTHER_CHANNEL",
      title: "您最初是從哪個管道得知本系統？ (單選「其他」需填寫文字)",
      description: "測試單選 is_other + requires_text",
      question_type: "single_choice",
      required: true,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },

    // 區塊 6: 擴充多元領域實務題 (Q16 ~ Q26)
    {
      order_num: 16,
      code: "Q6_DEPLOY_ENV",
      title: "您預計將本系統部署於何種環境？ (單選計分題)",
      description: "評估企業端自架與雲端需求",
      question_type: "single_choice",
      required: true,
      scoring_enabled: true,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 17,
      code: "Q6_CLOUD_PROVIDER",
      title: "您首選的雲端託管平台為何？ (條件題)",
      description: "SHOW IF Q6_DEPLOY_ENV in [公有雲 (AWS/GCP/Azure), 混合雲架構]",
      question_type: "single_choice",
      required: true,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: "SHOW IF Q6_DEPLOY_ENV in [公有雲 (AWS/GCP/Azure), 混合雲架構]",
      visibility_hint: "💡 請選擇您偏好的主要雲端供應商：",
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 18,
      code: "Q7_SECURITY_AUDIT",
      title: "您所在單位是否有定期的資安合規稽核要求？ (是非題)",
      description: "測試第二個是非題型",
      question_type: "yes_no",
      required: true,
      scoring_enabled: true,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 19,
      code: "Q7_COMPLIANCE_STANDARDS",
      title: "需符合的合規標準？ (複選不限數量)",
      description: "SHOW IF Q7_SECURITY_AUDIT equals 是",
      question_type: "multiple_choice",
      required: true,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: "SHOW IF Q7_SECURITY_AUDIT equals 是",
      visibility_hint: "💡 依據資安要求，請勾選適用的標準：",
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 20,
      code: "Q8_TEAM_SIZE",
      title: "您所屬團隊預計使用問卷系統之成員人數？ (數值 1~10000 人)",
      description: "測試數值大範圍 1~10000",
      question_type: "number",
      required: true,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: 1,
      max_value: 10000,
    },
    {
      order_num: 21,
      code: "Q8_LARGE_TEAM_BENEFIT",
      title: "大型團隊管理需求：請問您是否需要進階的問卷協同審核流程？",
      description: "SHOW IF Q8_TEAM_SIZE >= 50",
      question_type: "single_choice",
      required: false,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: "SHOW IF Q8_TEAM_SIZE >= 50",
      visibility_hint: "💡 您團隊規模較大，請評估協同審核需求：",
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 22,
      code: "Q9_UI_USABILITY",
      title: "您對新版介面視覺與響應式排版的滿意度？ (1~5分量表)",
      description: "標準 5 級分單選",
      question_type: "single_choice",
      required: true,
      scoring_enabled: true,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 23,
      code: "Q10_DOCUMENTATION",
      title: "官方文件與 Excel 匯入 SOP 的清晰程度？ (1~5分量表)",
      description: "標準 5 級分單選",
      question_type: "single_choice",
      required: true,
      scoring_enabled: true,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 24,
      code: "Q11_RECOMMEND_NPS",
      title: "您向同行推薦本系統的意願程度 (NPS 0~10 分)",
      description: "測試數值題 0~10 分",
      question_type: "number",
      required: true,
      scoring_enabled: true,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: 0,
      max_value: 10,
    },
    {
      order_num: 25,
      code: "Q12_GENERAL_ADVICE",
      title: "最後，您對本系統有任何其他寶貴建議或期許嗎？ (問答題)",
      description: "開放式非必填文字",
      question_type: "text",
      required: false,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
    {
      order_num: 26,
      code: "INFO_FINISH",
      title: "【感謝作答】已完成所有評估題目，請點選下方提交完成問卷",
      description: "結尾純資訊卡片",
      question_type: "info",
      required: false,
      scoring_enabled: false,
      reverse_score: false,
      visibility_rules: null,
      visibility_hint: null,
      min_selections: null,
      max_selections: null,
      min_value: null,
      max_value: null,
    },
  ];

  questionsData.forEach((q) => questionsSheet.addRow(q));

  // 2. Choices Sheet
  const choicesSheet = workbook.addWorksheet("choices");
  choicesSheet.columns = [
    { header: "question_code", key: "question_code", width: 18 },
    { header: "order_num", key: "order_num", width: 10 },
    { header: "label", key: "label", width: 35 },
    { header: "value", key: "value", width: 25 },
    { header: "score_enabled", key: "score_enabled", width: 15 },
    { header: "score", key: "score", width: 10 },
    { header: "is_other", key: "is_other", width: 12 },
    { header: "requires_text", key: "requires_text", width: 14 },
    { header: "is_none_of_above", key: "is_none_of_above", width: 16 },
  ];

  const choicesData = [
    // Q1 Choices
    { question_code: "Q1", order_num: 1, label: "非常不滿意", value: "very_dissatisfied", score_enabled: true, score: 1, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q1", order_num: 2, label: "不太滿意", value: "dissatisfied", score_enabled: true, score: 2, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q1", order_num: 3, label: "滿意", value: "satisfied", score_enabled: true, score: 3, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q1", order_num: 4, label: "非常滿意", value: "very_satisfied", score_enabled: true, score: 4, is_other: false, requires_text: false, is_none_of_above: false },

    // Q2_YESNO Choices
    { question_code: "Q2_YESNO", order_num: 1, label: "是", value: "yes", score_enabled: true, score: 2, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q2_YESNO", order_num: 2, label: "否", value: "no", score_enabled: true, score: 0, is_other: false, requires_text: false, is_none_of_above: false },

    // Q4_FEATURES_WANTED Choices
    { question_code: "Q4_FEATURES_WANTED", order_num: 1, label: "即時協同編輯 (+2分)", value: "realtime_collab", score_enabled: true, score: 2, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q4_FEATURES_WANTED", order_num: 2, label: "自動化工作流 (+3分)", value: "automation", score_enabled: true, score: 3, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q4_FEATURES_WANTED", order_num: 3, label: "進階統計報表 (+5分)", value: "advanced_stats", score_enabled: true, score: 5, is_other: false, requires_text: false, is_none_of_above: false },

    // Q4_INTEGRATIONS Choices
    { question_code: "Q4_INTEGRATIONS", order_num: 1, label: "Slack 官方整合 (+2分)", value: "slack", score_enabled: true, score: 2, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q4_INTEGRATIONS", order_num: 2, label: "Discord 整合 (+2分)", value: "discord", score_enabled: true, score: 2, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q4_INTEGRATIONS", order_num: 3, label: "其他自訂 Webhook (+1分)", value: "other_webhook", score_enabled: true, score: 1, is_other: true, requires_text: true, is_none_of_above: false },
    { question_code: "Q4_INTEGRATIONS", order_num: 4, label: "以上皆非 (完全無整合)", value: "none_of_above", score_enabled: true, score: 0, is_other: false, requires_text: false, is_none_of_above: true },

    // Q5_TECHNICAL_LEVEL Choices
    { question_code: "Q5_TECHNICAL_LEVEL", order_num: 1, label: "初學新手 (1分)", value: "lvl_novice", score_enabled: true, score: 1, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q5_TECHNICAL_LEVEL", order_num: 2, label: "中階熟練 (2分)", value: "lvl_intermediate", score_enabled: true, score: 2, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q5_TECHNICAL_LEVEL", order_num: 3, label: "進階專家 (3分)", value: "lvl_advanced", score_enabled: true, score: 3, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q5_TECHNICAL_LEVEL", order_num: 4, label: "架構大師 (特別獎勵 10分)", value: "lvl_master", score_enabled: true, score: 10, is_other: false, requires_text: false, is_none_of_above: false },

    // Q5_OUTAGE_HISTORY Choices
    { question_code: "Q5_OUTAGE_HISTORY", order_num: 1, label: "從未遭遇 (0分)", value: "zero_issues", score_enabled: true, score: 0, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q5_OUTAGE_HISTORY", order_num: 2, label: "曾遇重大斷線 (5分)", value: "major_issues", score_enabled: true, score: 5, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q5_OUTAGE_HISTORY", order_num: 3, label: "不確定 / 不願透露 (不計分)", value: "unspecified", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },

    // Q5_REVERSE_CONFUSION Choices (1~5反向)
    { question_code: "Q5_REVERSE_CONFUSION", order_num: 1, label: "非常不同意 (原始1分 -> 反轉得5分)", value: "strongly_disagree", score_enabled: true, score: 1, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q5_REVERSE_CONFUSION", order_num: 2, label: "不同意 (原始2分 -> 反轉得4分)", value: "disagree", score_enabled: true, score: 2, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q5_REVERSE_CONFUSION", order_num: 3, label: "普通 (原始3分 -> 反轉得3分)", value: "neutral", score_enabled: true, score: 3, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q5_REVERSE_CONFUSION", order_num: 4, label: "同意 (原始4分 -> 反轉得2分)", value: "agree", score_enabled: true, score: 4, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q5_REVERSE_CONFUSION", order_num: 5, label: "非常同意 (原始5分 -> 反轉得1分)", value: "strongly_agree", score_enabled: true, score: 5, is_other: false, requires_text: false, is_none_of_above: false },

    // Q5_OTHER_CHANNEL Choices
    { question_code: "Q5_OTHER_CHANNEL", order_num: 1, label: "搜尋引擎 (Google / Bing)", value: "search", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q5_OTHER_CHANNEL", order_num: 2, label: "社群媒體 (Twitter / LinkedIn)", value: "social", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q5_OTHER_CHANNEL", order_num: 3, label: "其他自訂來源 (請註明)", value: "other_src", score_enabled: false, score: null, is_other: true, requires_text: true, is_none_of_above: false },

    // Q6_DEPLOY_ENV Choices
    { question_code: "Q6_DEPLOY_ENV", order_num: 1, label: "地端內部伺服器 (On-Premises)", value: "on_prem", score_enabled: true, score: 3, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q6_DEPLOY_ENV", order_num: 2, label: "公有雲 (AWS/GCP/Azure)", value: "public_cloud", score_enabled: true, score: 3, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q6_DEPLOY_ENV", order_num: 3, label: "混合雲架構", value: "hybrid", score_enabled: true, score: 5, is_other: false, requires_text: false, is_none_of_above: false },

    // Q6_CLOUD_PROVIDER Choices
    { question_code: "Q6_CLOUD_PROVIDER", order_num: 1, label: "Amazon Web Services (AWS)", value: "aws", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q6_CLOUD_PROVIDER", order_num: 2, label: "Google Cloud Platform (GCP)", value: "gcp", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q6_CLOUD_PROVIDER", order_num: 3, label: "Microsoft Azure", value: "azure", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },

    // Q7_SECURITY_AUDIT Choices
    { question_code: "Q7_SECURITY_AUDIT", order_num: 1, label: "是", value: "yes", score_enabled: true, score: 3, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q7_SECURITY_AUDIT", order_num: 2, label: "否", value: "no", score_enabled: true, score: 0, is_other: false, requires_text: false, is_none_of_above: false },

    // Q7_COMPLIANCE_STANDARDS Choices
    { question_code: "Q7_COMPLIANCE_STANDARDS", order_num: 1, label: "ISO 27001", value: "iso27001", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q7_COMPLIANCE_STANDARDS", order_num: 2, label: "SOC 2 Type II", value: "soc2", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q7_COMPLIANCE_STANDARDS", order_num: 3, label: "GDPR / 台灣個資法", value: "privacy_law", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },

    // Q8_LARGE_TEAM_BENEFIT Choices
    { question_code: "Q8_LARGE_TEAM_BENEFIT", order_num: 1, label: "非常需要 (多層級簽核)", value: "high_need", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q8_LARGE_TEAM_BENEFIT", order_num: 2, label: "一般需要", value: "med_need", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q8_LARGE_TEAM_BENEFIT", order_num: 3, label: "不需要", value: "no_need", score_enabled: false, score: null, is_other: false, requires_text: false, is_none_of_above: false },

    // Q9_UI_USABILITY Choices
    { question_code: "Q9_UI_USABILITY", order_num: 1, label: "1分 (極差)", value: "1", score_enabled: true, score: 1, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q9_UI_USABILITY", order_num: 2, label: "2分 (差)", value: "2", score_enabled: true, score: 2, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q9_UI_USABILITY", order_num: 3, label: "3分 (普通)", value: "3", score_enabled: true, score: 3, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q9_UI_USABILITY", order_num: 4, label: "4分 (良好)", value: "4", score_enabled: true, score: 4, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q9_UI_USABILITY", order_num: 5, label: "5分 (極佳)", value: "5", score_enabled: true, score: 5, is_other: false, requires_text: false, is_none_of_above: false },

    // Q10_DOCUMENTATION Choices
    { question_code: "Q10_DOCUMENTATION", order_num: 1, label: "1分 (極不清晰)", value: "1", score_enabled: true, score: 1, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q10_DOCUMENTATION", order_num: 2, label: "2分 (略不清晰)", value: "2", score_enabled: true, score: 2, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q10_DOCUMENTATION", order_num: 3, label: "3分 (尚可)", value: "3", score_enabled: true, score: 3, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q10_DOCUMENTATION", order_num: 4, label: "4分 (清楚易懂)", value: "4", score_enabled: true, score: 4, is_other: false, requires_text: false, is_none_of_above: false },
    { question_code: "Q10_DOCUMENTATION", order_num: 5, label: "5分 (非常完整)", value: "5", score_enabled: true, score: 5, is_other: false, requires_text: false, is_none_of_above: false },
  ];

  choicesData.forEach((c) => choicesSheet.addRow(c));

  await workbook.xlsx.writeFile(outputPath);
  console.log(`Demo Complex Excel successfully generated at: ${outputPath}`);
}

// CLI direct run
if (require.main === module) {
  const dest = path.resolve(process.cwd(), "demo-complex-survey.xlsx");
  generateComplexSurveyExcel(dest).then(() => {
    console.log("26-question complex survey generated successfully!");
  });
}
